# -*- coding: utf-8 -*-
"""atividade-desenvolvida.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Muuist4MU_Jarq0dFvEEqH4pgv55ccW3
"""

#Desafio 1:



# Estrutura base para o exercício
import matplotlib.pyplot as plt

emoji_data = {

  "nome": "Smile",

  "grade": [

    [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)],

    [(255,255,0), (0,0,0),  (255,255,0), (0,0,0),  (255,255,0)],

    [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)],

    [(255,255,0), (0,0,0),  (0,0,0),  (0,0,0),  (255,255,0)],

    [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)]

  ]

}



nova_grade = []



for chave, valor in emoji_data.items():

  if chave == "grade":

    for linha in valor:

      nova_linha = []

      for pixel in linha:

        if pixel == (255,255,0): # amarelo

          novo_pixel = (pixel[0]//2, pixel[1]//2, pixel[2]//2)

          nova_linha.append(novo_pixel)

        else:

          nova_linha.append(pixel)

      nova_grade.append(nova_linha)



emoji_data["grade"] = nova_grade



print(emoji_data)

plt.imshow(emoji_data["grade"])
plt.show()

#Desafio 2:



biblioteca_musical = {

  "Toques": [

    {"Alegre": ([440, 480], [520, 560])},

    {"Triste": ([200, 150], [100, 50])}

  ]

}



for lista in biblioteca_musical["Toques"]:

  for nome, matriz in lista.items():

    nova_matriz = []



    for i in range(len(matriz[0])): # percorre colunas

      nova_linha = []

      for j in range(len(matriz)): # percorre linhas

        nova_linha.append(matriz[j][i])

      nova_matriz.append(nova_linha)



    lista.update({nome: nova_matriz})



print(biblioteca_musical)

#Desafio 3:
import matplotlib.pyplot as plt


playlist_imagens = {

  "galeria": [

    {"emoji1": [(255,255,0), (0,0,0)]},

    {"emoji2": [(100,100,100), (50,50,50)]}

  ]

}



for item in playlist_imagens["galeria"]:

  for nome in list(item.keys()):

    pixels = item[nome]



    nova_lista = []



    for pixel in pixels:

      novo_pixel = (pixel[0]+10, pixel[1]+10, pixel[2]+10)

      nova_lista.append(novo_pixel)



    item.pop(nome)

    item.insert if False else None

    item[nome] = nova_lista



print(playlist_imagens)
plt.imshow(emoji_data["grade"])
plt.show()