# -*- coding: utf-8 -*-
"""atividade-desenvolvida.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oiapi86_AsAAGaMljk1FU-QDv4Q8H5-R
"""

### PARTE 1: O Algoritmo do Microclima Local



def analisar_microclima():

  print("-" * 40)

  print("ANÁLISE DE MICROCLIMA E CONFORTO URBANO")

  print("-" * 40)



  # Dados coletados: [Nome do Local, Temperatura (°C), Umidade (%), IQA]

  # Valores estimados para os horários de pico nos locais definidos

  dados_locais = [

    ["Praça Jauarapa (Área Verde)", 26, 65, 35],

    ["Unicid - Tatuapé (Urbano)", 30, 45, 85],

    ["Terminal Tatuapé (Fluxo Intenso)", 32, 40, 130]

  ]



  # 1º Loop: Itera sobre as listas de locais

  for local in dados_locais:

    nome_local = local[0]

    temp = 0

    umid = 0

    iqa = 0



    # 2º Loop (Aninhado): Itera sobre as métricas dentro da lista do local específico

    for indice, metrica in enumerate(local):

      if indice == 1:

        temp = metrica

      elif indice == 2:

        umid = metrica

      elif indice == 3:

        iqa = metrica



    # Avaliação do IQA usando match-case com guardas (if)

    classificacao_ar = ""

    match iqa:

      case valor if valor <= 40:

        classificacao_ar = "Boa (Verde) - Sem riscos"

      case valor if valor <= 80:

        classificacao_ar = "Moderada (Amarelo) - Pessoas sensíveis podem sentir fadiga"

      case valor if valor <= 120:

        classificacao_ar = "Ruim (Laranja) - Sintomas como tosse seca"

      case valor if valor <= 200:

        classificacao_ar = "Muito Ruim (Vermelho) - Toda população pode apresentar sintomas"

      case _:

        classificacao_ar = "Péssima (Roxo) - Riscos graves à saúde"



    # Matemática complexa: Fórmula própria de "Nota de Conforto Urbano" (0 a 10)

    # Lógica: Parte de 10, penaliza temperaturas distantes de 24°C, penaliza poluição (IQA alto) e bonifica boa umidade.

    penalidade_temp = abs(temp - 24) * 0.5

    penalidade_poluicao = iqa * 0.05

    bonus_umidade = umid * 0.02



    nota_conforto = 10 - penalidade_temp - penalidade_poluicao + bonus_umidade



    # Garante que a nota fique entre 0 e 10

    if nota_conforto > 10:

      nota_conforto = 10

    elif nota_conforto < 0:

      nota_conforto = 0



    print(f"\nLocal: {nome_local}")

    print(f"Temperatura: {temp}°C | Umidade: {umid}% | IQA: {iqa}")

    print(f"Qualidade do Ar: {classificacao_ar}")

    print(f"Nota de Conforto Urbano: {nota_conforto:.1f}/10.0")



# Executando a função principal

analisar_microclima()



### PARTE 2: Navegação e Evacuação Espacial



def simulador_evacuacao_real():

    print("\n" + "="*55)

    print("SISTEMA DE EMERGÊNCIA: PROTOCOLO DE EVACUAÇÃO - CASA")

    print("="*55)



    # 1. Definição dos nós com base no mapeamento exato

    rota_fuga = [

        "Meu Quarto",

        "Lavanderia",

        "Cozinha",

        "Sala de Estar",

        "Corredor",

        "Garagem",

        "Rua"

    ]



    # 2. Estado de cada nó (Obstáculos e Facilitadores)

    estado_nó = [

        "caminho livre",

        "piso molhado",

        "caminho livre",

        "chave do portão",

        "fumaça",

        "portão trancado",

        "segurança"

    ]



    # Variáveis de controle do agente

    posicao_atual = 0

    energia = 100

    inventario = []

    sucesso = False



    # 3. Loop While: Tentativa contínua de navegação

    while posicao_atual < len(rota_fuga) and energia > 0:

        local = rota_fuga[posicao_atual]

        condicao = estado_nó[posicao_atual]



        print(f"\n[AGENTE] Local atual: {local.upper()}")

        print(f"[STATUS] Condição: {condicao}")

        print(f"[STATUS] Energia restante: {energia}%")



        # 4. If Aninhado: Avaliação lógica

        if condicao == "caminho livre":

            print(">> Caminho desobstruído. Avançando para o próximo cômodo...")

            posicao_atual += 1

            energia -= 5



        elif condicao == "piso molhado":

            print(">> ALERTA: Risco de escorregar. Movimentação cautelosa exigida.")

            posicao_atual += 1

            energia -= 15 # Gasto extra por cautela



        elif condicao == "chave do portão":

            print(">> Facilitador encontrado: Chave da Garagem coletada!")

            if "chave" not in inventario:

                inventario.append("chave")

            posicao_atual += 1

            energia -= 5



        elif condicao == "fumaça":

            print(">> ALERTA CRÍTICO: Fumaça densa! Esforço respiratório alto.")

            posicao_atual += 1

            energia -= 25 # Penalidade severa



        elif condicao == "portão trancado":

            # Subcondição: Verificando o inventário

            if "chave" in inventario:

                print(">> Utilizando chave... Portão da garagem destrancado!")

                posicao_atual += 1

                energia -= 5

            else:

                print(">> BLOQUEIO: O portão está trancado e você esqueceu a chave!")

                print(">> O agente precisa voltar à Sala de Estar para procurar a chave.")

                # Retrocede dois cômodos (volta do Corredor para a Sala)

                posicao_atual -= 2

                energia -= 15



        elif condicao == "segurança":

            print(">> SUCESSO ABSOLUTO: O agente chegou à Rua e está a salvo!")

            sucesso = True

            break



    # Verificação final

    if not sucesso:

        print("\n[FALHA] O agente exauriu suas forças a caminho da rua.")



# Execução

simulador_evacuacao_real()